coverage:
  round: nearest
  ignore:
    - "**/mocks"
    - "cmd"
  status:
    project:
      default:
        threshold: 0.5
    patch: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes
  branches: null